/* =========================================================
   Sample client reviews (PLACEHOLDER CONTENT)
   ---------------------------------------------------------
   These are sample testimonials for layout/demo purposes.
   Replace with genuine client reviews before going live.
   Each item: { name, tag, rating (1-5), text }
   Valid tags: Family, Consumer, Civil, Property,
               Cheque Bounce, Arbitration
   ========================================================= */

window.REVIEWS = [
  { name: "Ramesh Iyer", tag: "Family", rating: 5, text: "Advocate Kiran handled my divorce matter with great patience and sensitivity. He explained every step clearly and never rushed me. Truly grateful for his guidance." },
  { name: "Anjali Rao", tag: "Family", rating: 5, text: "Compassionate and professional. My custody case was emotionally hard, but he kept me informed and confident throughout. Highly recommend." },
  { name: "Suresh Kumar", tag: "Cheque Bounce", rating: 5, text: "My cheque bounce case under Section 138 was resolved faster than I expected. Clear advice and prompt filing. Excellent work." },
  { name: "Priya Menon", tag: "Property", rating: 5, text: "Before buying our flat in Jayanagar, Mr. Kiran gave a detailed title opinion that saved us from a risky deal. Very thorough." },
  { name: "Mohammed Imran", tag: "Civil", rating: 5, text: "He represented me in a property recovery suit and the outcome was excellent. Honest about timelines and very approachable." },
  { name: "Deepa Shetty", tag: "Consumer", rating: 5, text: "Got my refund from a builder after months of being ignored. The consumer complaint was drafted perfectly. Thank you, sir." },
  { name: "Venkatesh Reddy", tag: "Arbitration", rating: 5, text: "Our business dispute was settled through arbitration without dragging into court for years. Practical and result-oriented advice." },
  { name: "Lakshmi Narayan", tag: "Family", rating: 4, text: "Very supportive during a difficult maintenance case. Kept things transparent and fair. Would consult again." },
  { name: "Arjun Pillai", tag: "Cheque Bounce", rating: 5, text: "Recovered my dues from a defaulter who had ignored me for a year. Strong follow-up and clear communication." },
  { name: "Sneha Gowda", tag: "Property", rating: 5, text: "Helped with registration and conveyancing of our site. All paperwork was handled smoothly and on time." },
  { name: "Rajesh Nair", tag: "Civil", rating: 5, text: "Professional, well-prepared and honest. My civil suit was argued thoroughly. Trustworthy advocate." },
  { name: "Kavya Hegde", tag: "Consumer", rating: 5, text: "Filed a complaint against an online retailer and won. He made a complicated process feel simple." },
  { name: "Manjunath Swamy", tag: "Property", rating: 5, text: "Detailed property opinion before purchase. Pointed out an encumbrance the broker never mentioned. Saved us a lot." },
  { name: "Fatima Begum", tag: "Family", rating: 5, text: "Handled my matrimonial matter with dignity and confidentiality. I felt heard and respected throughout." },
  { name: "Karthik Subramanian", tag: "Arbitration", rating: 4, text: "Good experience resolving a contract dispute via arbitration. Clear strategy and fair fees." },
  { name: "Divya Prakash", tag: "Civil", rating: 5, text: "Won an injunction in my favour. He is sharp, prepared and genuinely cares about clients." },
  { name: "Naveen Kumar", tag: "Cheque Bounce", rating: 5, text: "Quick legal notice and a strong case got my money back. Couldn't have asked for better support." },
  { name: "Shruthi Acharya", tag: "Consumer", rating: 5, text: "My insurance claim rejection was challenged successfully. Patient explanations at every stage." },
  { name: "Gopal Krishna", tag: "Property", rating: 5, text: "Reliable advice on a partition matter in our family property. Calm, balanced and very knowledgeable." },
  { name: "Asha Verma", tag: "Family", rating: 5, text: "He guided me through mutual consent divorce smoothly. Respectful and prompt with every query." },
  { name: "Vikram Desai", tag: "Civil", rating: 5, text: "Excellent representation in a tenancy dispute. He is realistic and never over-promises." },
  { name: "Pooja Bhat", tag: "Consumer", rating: 4, text: "Helped resolve a defective product complaint. Responsive on calls and WhatsApp." },
  { name: "Sandeep Jain", tag: "Arbitration", rating: 5, text: "Handled a vendor payment arbitration efficiently. Saved months of litigation." },
  { name: "Meera Krishnan", tag: "Property", rating: 5, text: "Thorough due diligence on our apartment purchase. Documentation was flawless." },
  { name: "Harish Babu", tag: "Cheque Bounce", rating: 5, text: "Professional handling of my NI Act case. He kept me updated at every hearing." },
  { name: "Nisha Reddy", tag: "Family", rating: 5, text: "Sensitive and strong advocate for my domestic matter. I always felt protected." },
  { name: "Praveen Shetty", tag: "Civil", rating: 5, text: "Recovered possession of my land after a long dispute. Persistent and meticulous." },
  { name: "Ananya Das", tag: "Consumer", rating: 5, text: "Got compensation from a service provider. He fights for what's right." },
  { name: "Rahul Mehta", tag: "Arbitration", rating: 4, text: "Smooth arbitration of a partnership disagreement. Balanced and pragmatic." },
  { name: "Sushma Patil", tag: "Property", rating: 5, text: "Clear legal opinion on a joint development agreement. Explained risks in plain language." },
  { name: "Aravind Rao", tag: "Cheque Bounce", rating: 5, text: "Fast and firm. My dishonoured cheque case was filed within days." },
  { name: "Bhavana Hegde", tag: "Family", rating: 5, text: "Guided me kindly through a sensitive separation. Truly client-focused." },
  { name: "Sanjay Gupta", tag: "Civil", rating: 5, text: "A reliable advocate who is honest about your chances. Won my recovery suit." },
  { name: "Reshma Khan", tag: "Consumer", rating: 5, text: "Helped me hold a builder accountable for delays. Very persistent." },
  { name: "Tarun Shenoy", tag: "Arbitration", rating: 5, text: "Resolved a commercial lease dispute through arbitration. Efficient and clear." },
  { name: "Geetha Murthy", tag: "Property", rating: 4, text: "Helpful with khata transfer and registration. Made the process stress-free." },
  { name: "Mahesh Kulkarni", tag: "Cheque Bounce", rating: 5, text: "Strong legal notice that got immediate response from the defaulter. Brilliant." },
  { name: "Swathi Reddy", tag: "Family", rating: 5, text: "Handled my maintenance plea with care and got a fair order. Forever grateful." },
  { name: "Imtiaz Ahmed", tag: "Civil", rating: 5, text: "Detailed preparation and confident arguments. My case was in safe hands." },
  { name: "Nandini Rao", tag: "Consumer", rating: 5, text: "Won a refund from an e-commerce company. He simplified everything for me." },
  { name: "Prakash Naidu", tag: "Arbitration", rating: 5, text: "Quick, cost-effective resolution of a supplier dispute. Highly satisfied." },
  { name: "Sahana Bhat", tag: "Property", rating: 5, text: "Excellent title verification before our plot purchase. Very dependable." },
  { name: "Dinesh Kumar", tag: "Cheque Bounce", rating: 4, text: "Good outcome in my cheque case. Honest about the process and fees." },
  { name: "Roopa Shetty", tag: "Family", rating: 5, text: "Treated my divorce matter with great empathy. I never felt alone in it." },
  { name: "Abhishek Rao", tag: "Civil", rating: 5, text: "Methodical and prepared. He won an interim relief that mattered a lot to me." },
  { name: "Yamini Reddy", tag: "Consumer", rating: 5, text: "Got my faulty appliance replaced after a forum complaint. Excellent guidance." },
  { name: "Faisal Sheikh", tag: "Arbitration", rating: 5, text: "Settled a construction payment dispute fairly. Professional throughout." },
  { name: "Chaitra Gowda", tag: "Property", rating: 5, text: "Helped us with sale deed drafting and registration. Smooth and quick." },
  { name: "Ravindra Joshi", tag: "Cheque Bounce", rating: 5, text: "Recovered a large sum from a bounced cheque. Diligent and reliable." },
  { name: "Pallavi Nair", tag: "Family", rating: 5, text: "Calm, clear and supportive during my custody case. Highly recommended." },
  { name: "Srinivas Murthy", tag: "Civil", rating: 5, text: "Honest counsel who won't waste your time or money. Won my civil matter." },
  { name: "Aisha Khan", tag: "Consumer", rating: 4, text: "Resolved a bank service complaint efficiently. Responsive and patient." },
  { name: "Manoj Pai", tag: "Arbitration", rating: 5, text: "Professional handling of a JV dispute through arbitration. Great results." },
  { name: "Vidya Rao", tag: "Property", rating: 5, text: "Spotted a title defect before our purchase. His opinion was invaluable." },
  { name: "Kiran Kumar", tag: "Cheque Bounce", rating: 5, text: "Strong representation in my NI Act case. Clear and confident at every hearing." },
  { name: "Shilpa Reddy", tag: "Family", rating: 5, text: "Helped me secure maintenance for my children. Compassionate and effective." },
  { name: "Ganesh Bhat", tag: "Civil", rating: 5, text: "Won a long-pending boundary dispute. Patient, persistent and thorough." },
  { name: "Neha Sharma", tag: "Consumer", rating: 5, text: "Got compensation for a cancelled service. He made the law accessible to me." },
  { name: "Arun Prabhu", tag: "Arbitration", rating: 4, text: "Efficient arbitration of a rental dispute. Saved us from a long court battle." },
  { name: "Lavanya Iyer", tag: "Property", rating: 5, text: "Detailed conveyancing for our new home. Every clause was explained clearly." },
  { name: "Santosh Hegde", tag: "Cheque Bounce", rating: 5, text: "Recovered my money quickly through a well-drafted complaint. Excellent." },
  { name: "Rekha Devi", tag: "Family", rating: 5, text: "Guided me with dignity through a hard time. Truly a trustworthy advocate." },
  { name: "Naveen Shetty", tag: "Civil", rating: 5, text: "Sharp legal mind. He handled my contractual dispute with great skill." },
  { name: "Tanvi Joshi", tag: "Consumer", rating: 5, text: "Won a deficiency-in-service case against a telecom company. Very capable." },
  { name: "Mahesh Rao", tag: "Arbitration", rating: 5, text: "Resolved our shareholders' dispute amicably. Practical and fair-minded." },
  { name: "Supriya Nair", tag: "Property", rating: 4, text: "Good guidance on a gift deed and registration. Smooth process overall." },
  { name: "Vivek Anand", tag: "Cheque Bounce", rating: 5, text: "Prompt action and a strong case. My dues were recovered with interest." },
  { name: "Anita Pillai", tag: "Family", rating: 5, text: "Patient and understanding during my divorce. Made a tough phase easier." },
  { name: "Rohan Kamath", tag: "Civil", rating: 5, text: "Excellent in court and in advice. My civil dispute was resolved in my favour." },
  { name: "Pooja Reddy", tag: "Consumer", rating: 5, text: "Got my home loan grievance addressed. Knowledgeable and reassuring." },
  { name: "Sadiq Pasha", tag: "Arbitration", rating: 5, text: "Handled a vendor contract arbitration with great clarity. Strongly recommend." },
  { name: "Bhagya Lakshmi", tag: "Property", rating: 5, text: "Verified our property documents thoroughly. Honest and dependable counsel." },
  { name: "Akash Verma", tag: "Cheque Bounce", rating: 4, text: "Solid handling of my cheque dishonour case. Kept me informed throughout." },
  { name: "Madhuri Rao", tag: "Family", rating: 5, text: "Sensitive and firm advocate for my matrimonial matter. Genuinely caring." },
  { name: "Sunil Dutt", tag: "Civil", rating: 5, text: "Recovered possession of my shop after years. Persistent and committed." },
  { name: "Keerthi Shetty", tag: "Consumer", rating: 5, text: "Won a refund case against a travel company. Clear and effective help." },
  { name: "Raghav Menon", tag: "Arbitration", rating: 5, text: "Professional arbitration of a business dispute. Saved time and money." },
  { name: "Ananya Reddy", tag: "Property", rating: 5, text: "Detailed legal opinion before buying our plot. Avoided a costly mistake." },
  { name: "Mohan Das", tag: "Cheque Bounce", rating: 5, text: "Excellent recovery work on a bounced cheque. Strong and timely action." },
  { name: "Sneha Kulkarni", tag: "Family", rating: 5, text: "Handled my divorce with empathy and professionalism. Highly grateful." },
  { name: "Vinay Kumar", tag: "Civil", rating: 4, text: "Honest, prepared and reliable. He won my civil recovery case." },
  { name: "Deepika Rao", tag: "Consumer", rating: 5, text: "Got compensation after a builder's delay. He stood by me throughout." },
  { name: "Irfan Ali", tag: "Arbitration", rating: 5, text: "Resolved a partnership dispute via arbitration. Calm and effective." },
  { name: "Shwetha Pai", tag: "Property", rating: 5, text: "Smooth registration and conveyancing of our new flat. Stress-free." },
  { name: "Girish Rao", tag: "Cheque Bounce", rating: 5, text: "Recovered my money efficiently. Clear advice and firm follow-through." },
  { name: "Aparna Menon", tag: "Family", rating: 5, text: "Compassionate guidance through a custody matter. Always responsive." },
  { name: "Nikhil Shenoy", tag: "Civil", rating: 5, text: "Thorough preparation and strong arguments. Won my property suit." },
  { name: "Reena Joseph", tag: "Consumer", rating: 5, text: "Helped me win a consumer forum case against a hospital. Very supportive." },
  { name: "Sameer Khan", tag: "Arbitration", rating: 4, text: "Efficient arbitration of a service contract dispute. Fair and clear." },
  { name: "Triveni Rao", tag: "Property", rating: 5, text: "Excellent title opinion and documentation help. Truly dependable." },
  { name: "Ashok Reddy", tag: "Cheque Bounce", rating: 5, text: "Strong legal notice and a quick recovery. Professional all the way." },
  { name: "Jyothi Hegde", tag: "Family", rating: 5, text: "Handled my maintenance case with care. Got a just and fair result." },
  { name: "Pramod Shetty", tag: "Civil", rating: 5, text: "Reliable and meticulous. He resolved my tenancy dispute successfully." },
  { name: "Sania Sheikh", tag: "Consumer", rating: 5, text: "Won my complaint against an online seller. Patient and knowledgeable." },
  { name: "Harsha Vardhan", tag: "Arbitration", rating: 5, text: "Resolved a commercial dispute through arbitration. Pragmatic and fast." },
  { name: "Lata Krishnan", tag: "Property", rating: 5, text: "Detailed due diligence before our purchase. Honest and very thorough." },
  { name: "Suhas Rao", tag: "Cheque Bounce", rating: 5, text: "Recovered my dues with a well-prepared case. Highly professional." },
  { name: "Bindiya Nair", tag: "Family", rating: 5, text: "Supportive and clear throughout my divorce. I always felt in good hands." },
  { name: "Rakesh Gowda", tag: "Civil", rating: 5, text: "Won a difficult civil matter with patience and skill. Truly grateful." },
  { name: "Anusha Reddy", tag: "Consumer", rating: 5, text: "Got my refund after a long fight. He never gave up on my case." }
];
